### ISSUE TITLE
 throw e; // process.nextTick error, or 'error' event on first tick

### ISSUE THREAD

**Issue by mars1985** [tadast/webattle.js#3]
Hello, I have setup a local windows 7 server that I was going to test this out and it apears that when I run node server.js  it is having trouble locating the module? Any thoughts? Thank you for your help.

```
C:\wamp\www\webattle>node server.js

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Cannot find module "C:\\wamp\\www\\webattle/lib/serializer" from director
y "C:\\wamp\\www\\webattle"
    at Wrap.require (C:\wamp\www\webattle\node_modules\browserify\lib\wrap.js:31
4:19)
    at include (C:\wamp\www\webattle\node_modules\browserify\lib\wrap.js:277:14)

    at Array.forEach (native)
    at Wrap.requireMultiple (C:\wamp\www\webattle\node_modules\browserify\lib\wr
ap.js:255:16)
    at Wrap.require (C:\wamp\www\webattle\node_modules\browserify\lib\wrap.js:28
9:21)
    at C:\wamp\www\webattle\node_modules\browserify\index.js:79:7
    at Object.<anonymous> (C:\wamp\www\webattle\server.js:9:32)
    at Module._compile (module.js:432:26)
    at Object..js (module.js:450:10)
    at Module.load (module.js:351:31)
```

**Comment by tadast** [comment]
I haven't tested it on windows, it looks I have hardcoded the paths using forward slash, whereas windows is using backwards slashes `C:\\wamp\\www\\webattle/lib/serializer`.

It'd be nice if you could try to fix this issue and get a OS-aware paths in require statements and submit a pull request :)

**Comment by mars1985** [comment]
Okay, I will give that a try - thank you!

**Comment by mars1985** [comment]
I found it easier to setup a ubuntu server for live testing - windows is still a bit shakey when it comes to node.js
